server:
  port: 8761                          # 指定该Eureka实例的端口
spring:
  application:
    name: eureka-server               # 项目名称尽量用小写
eureka:
  instance:
    hostname: st-eureka-server        # 指定该Eureka实例的主机名
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    responseCacheUpdateInvervalMs: 3000
    responseCacheAutoExpirationInSeconds: 180
    eviction-interval-timer-in-ms: 3000
